apiVersion: v1
kind: Service
metadata:
  name: open-data-web-service
  namespace: open-data-app
spec:
  type: NodePort
  selector:
    app: open-data-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
