name: CI (self-hosted)

on:
  workflow_dispatch:

jobs:
  run-local:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run module locally
        shell: powershell
        run: |
          cd "I:\3 курс\2 семсетр\Середовище та компоненти розробки\Lab1\open-data-ai-analytics"
          if (!(Test-Path "artifacts/visualization")) { mkdir "artifacts/visualization" }
          python src/visualization.py
        
        

      - name: Upload local results
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-visualization-local
          path: artifacts/visualization/