name: CI (self-hosted)

on:
  workflow_dispatch:

jobs:
  run-local:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run module locally
        run: |
          mkdir -p artifacts/visualization
          python src/visualization.py
        shell: bash

      - name: Upload local results
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-visualization-local
          path: artifacts/visualization/