name: CI (self-hosted)

on:
  workflow_dispatch:

jobs:
  run-local:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run module locally
        run: |
          # Створюємо папку для результатів, якщо її ще немає
          if not exist artifacts\visualization mkdir artifacts\visualization
          
          # Запуск скрипта. Тепер він побачить локальні файли в папці data/
          # Використовуємо перенаправлення виводу в лог-файл
          python src/visualization.py > artifacts/visualization/run.log 2>&1
        shell: cmd

      - name: Upload local results
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-visualization-local
          path: artifacts/visualization/